name: Automated Version Bump
description: Automated version bump for npm packages.
runs:
  using: node16
  main: index.js
branding:
  icon: chevron-up
  color: blue
inputs:
  PARSE_APP_ID:
    description: 'Parse Application ID'
    default: ''
    required: true
  PARSE_SERVER_URL:
    description: 'Parse Server URL w/ trailing slash'
    default: ''
    required: true
  PARSE_MASTER_KEY:
    description: 'Parse Master Key'
    default: ''
    required: true
outputs:
  newTag:
    description: 'The newly created tag'
